name: puskeswan_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # --- PAKET UTAMA ---
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.12.0
  pdf: ^3.11.3
  printing: ^5.14.2
  intl: ^0.20.2
  csv: ^6.0.0
  file_saver: ^0.3.1
  sqflite: ^2.4.2
  path: ^1.9.1
  connectivity_plus: ^7.0.0
  google_fonts: ^6.3.3
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  package_info_plus: ^9.0.0
  
  # --- PENTING BUAT DOWNLOAD DI WEB ---
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

# --- SETTINGAN LOGO ---
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48
  linux:
    generate: true
    image_path: "assets/logo.png"